config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :pastes, only: %w[new create index show destroy], param: :permalink do
    get :raw
  end

  resource :pastes do
    post :spam
  end

  resources :terms, only: %i[index new create destroy]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get '/up' => 'rails/health#show'

  # Omniauth support
  post '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/:provider/callback', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :auths, only: %i[index new create destroy]

  # Defines the root path route ("/")
  root 'pastes#new'

  # Old API support
  post '/', to: 'oldapi#create'
  get '/:permalink', to: 'oldapi#redirect'
end

app/models/term.rb
# frozen_string_literal: true

# The term model to delete or moderate posts
class Term < ApplicationRecord
  enum :subject, %w[author title code]
  enum :action, %w[mark_spam remove]
end

app/controllers/terms_controller.rb
# frozen_string_literal: true

# The page for setting up terms
class TermsController < ApplicationController
  before_action :set_term, only: :destroy
  after_action :verify_authorized
  after_action :verify_policy_scoped, only: :index

  def index
    authorize Term.new
    @terms = policy_scope(Term)
  end

  def new
    @term = authorize Term.new
  end

  def create
    @term = authorize Term.new(term_params)

    if @term.save
      redirect_to terms_url, notice: t(:term_create)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    authorize @term

    @term.destroy

    redirect_to terms_url, notice: t(:term_destroyed)
  end

  private

  def set_term
    @term = Term.find(params[:term_id] || params[:id])

    redirect_to terms_url, alert: t(:term_not_found) unless @term
  end

  def term_params
    params.require(:term).permit(:subject, :content, :action)
  end
end

app/views/terms/index.html.haml
%h1= t(:terms_list)
- if policy(Term.new).new?
  = link_to(t(:create),
            new_term_path, class: 'btn btn-primary mb-3')
.list-group
  - @terms.each do |term|
    .list-group-item.d-flex.justify-content-between
      %span
        = term.action.humanize
        %b= term.subject
        with content:
        "#{term.content}"
      = button_to t(:remove), term_path(term),
                  method: :delete,
                  class: 'btn p-0 text-danger'

app/views/terms/new.html.haml
%h1= t(:create_term)
= form_for @term do |f|
  - @term.errors.full_messages.each do |message|
    .alert.alert-danger
      = message

  .form-floating.mb-3
    = f.select :subject, Term.subjects.keys.index_by(&:humanize),
               {}, { class: 'form-select' }
    = f.label :subject, class: 'form-label'
  .form-floating.mb-3
    = f.text_field :content, class: 'form-control'
    = f.label :content, class: 'form-label'
  .form-floating.mb-3
    = f.select :action, Term.actions.keys.index_by(&:humanize),
               {}, { class: 'form-select' }
    = f.label :action, class: 'form-label'
  = f.submit t(:save), class: 'btn btn-primary'