config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :pastes, only: %w[new create index show destroy], param: :permalink do
    get :raw
  end

  resource :pastes do
    post :spam
  end

  resources :terms, only: %i[index new create destroy]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get '/up' => 'rails/health#show'

  # Omniauth support
  post '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/:provider/callback', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :auths, only: %i[index new create destroy]

  # Defines the root path route ("/")
  root 'pastes#new'

  # Old API support
  post '/', to: 'oldapi#create'
  get '/:permalink', to: 'oldapi#redirect'
end

app/models/auth.rb
# frozen_string_literal: true

# The keys for users
class Auth < ApplicationRecord
  belongs_to :user
  has_secure_token :key, length: 36

  scope :for_user, ->(current_user) { where(user: current_user) }

  def self.from_omniauth(response)
    info = response.info
    username = info['nickname'] || info['name']
    user = User.find_or_create_by!(username:) do |u|
      u.email = info['email']
    end
    find_or_create_by!(uid: response['uid'], name: response['provider'], user:)
  end
end

app/controllers/auths_controller.rb
# frozen_string_literal: true

# Implementation of authentication in the application
class AuthsController < ApplicationController
  before_action :set_auth, only: [:destroy]
  after_action :verify_authorized
  after_action :verify_policy_scoped, only: :index

  def index
    @auths = policy_scope(Auth)&.for_user(current_user)
    authorize Auth
  end

  def new
    @auth = authorize Auth.new
  end

  def create
    defaults = {}
    defaults[:user_id] = current_user.id if user_signed_in?
    @auth = authorize Auth.new(auth_params.merge(defaults))

    if @auth.save
      redirect_to auths_url, notice: t(:auth_create)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    if user_signed_in? && @auth.user == current_user
      @auth.destroy
      redirect_to auths_url, notice: t(:auth_destroyed)
    else
      redirect_to auth_url(@auth), alert: t(:auth_not_destroyed)
    end
  end

  private

  def set_auth
    @auth = authorize Auth.find(params[:id])

    redirect_to auths_url, alert: t(:auth_not_found) unless @auth
  end

  def auth_params
    params.require(:auth).permit(:name)
  end
end

app/views/auths/index.html.haml
.d-flex.justify-content-between.align-items-center
  %h1= t(:auths)
  = link_to t(:auth_new), new_auth_path, class: 'btn btn-primary'
.list-group
  - @auths.each do |auth|
    .list-group-item
      .row
        .col-md-6.my-auto
          = auth.name
        .col-md-6.d-flex.align-items-center
          .input-group{ data: { controller: 'clipboard' } }
            = tag.input type: 'text', value: auth.key, class: 'form-control',
                        'data-clipboard-target': 'source', readonly: 'readonly'
            = tag.button class: 'btn btn-secondary border',
                         'data-action': 'clipboard#copy',
                         title: t(:copy_to_clipboard) do
              %i.fas.fa-clipboard
              .visually-hidden= t(:copy_to_clipboard)
          .dropdown.ms-2
            %button.btn.btn-secondary{ type: 'button', 'aria-expanded': 'false',
                                       'data-bs-toggle': 'dropdown',
                                       title: t(:options) }
              %i.fas.fa-ellipsis-vertical
              .visually-hidden= t(:options)
            %ul.dropdown-menu.dropdown-menu-end
              - unless auth.id == session[:auth_id]
                %li
                  = button_to t(:auth_remove), auth_path(auth),
                              method: :delete,
                              class: 'dropdown-item text-danger'

app/views/auths/new.html.haml
%h1= t(:auth_new)
%div
  = form_for @auth do |f|
    - @auth.errors.full_messages.each do |message|
      .alert.alert-danger
        = message

    .form-floating.mb-3
      = f.text_field :name, placeholder: :title, class: 'form-control'
      = f.label :name, class: 'form-label'
    .d-flex.justify-content-end.align-items-center
      = f.submit t(:save), class: 'btn btn-primary'