config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :pastes, only: %w[new create index show destroy], param: :permalink do
    get :raw
  end

  resource :pastes do
    post :spam
  end

  resources :terms, only: %i[index new create destroy]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get '/up' => 'rails/health#show'

  # Omniauth support
  post '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/:provider/callback', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :auths, only: %i[index new create destroy]

  # Defines the root path route ("/")
  root 'pastes#new'

  # Old API support
  post '/', to: 'oldapi#create'
  get '/:permalink', to: 'oldapi#redirect'
end

app/models/paste.rb
# frozen_string_literal: true

# The primary application model for storing pastes
class Paste < ApplicationRecord
  self.implicit_order_column = 'created_at'

  PERIODS = [[I18n.t(:months, count: 3), 3.months],
             [I18n.t(:months, count: 1), 1.month],
             [I18n.t(:weeks, count: 2), 2.weeks],
             [I18n.t(:weeks, count: 1), 1.week],
             [I18n.t(:days, count: 3), 3.days],
             [I18n.t(:days, count: 1), 1.day],
             [I18n.t(:hours, count: 12), 12.hours],
             [I18n.t(:hours, count: 6), 6.hours],
             [I18n.t(:hours, count: 1), 1.hour],
             [I18n.t(:minutes, count: 30), 30.minutes]].freeze

  has_one_attached :content
  belongs_to :user, optional: true
  belongs_to :marked_by, class_name: 'User', optional: true

  enum :marked_kind, %w[unclassified ham spam]

  attribute :author, default: -> { Paste.default_author }
  attribute :remove_at, default: -> { Time.zone.now + 7.days.seconds }

  before_save :train_classifier
  before_save :delete_spam
  before_save :check_terms
  before_create :create_permalink
  after_save :enqueue_removal

  validates :content, presence: true
  validate :content_size
  validate :remove_at_max

  # Avoiding the case of showing anonymous users' private pastes to anonymous users
  scope :by_author, ->(user) { where(user:).where.not(user: nil) }

  def to_param
    permalink
  end

  def code=(value)
    return if value.empty?

    io = StringIO.new(value)
    default_mime = Marcel::Magic.new('text/plain')
    mime = Marcel::Magic.by_magic(value) || default_mime
    filename = "#{SecureRandom.hex(16)}.#{mime.extensions.first}"
    blob = ActiveStorage::Blob.create_and_upload!(io:, filename:)
    content.attach(blob)
  end

  def code
    return '' unless content&.attachment

    content.attachment.open(&:read).force_encoding('utf-8')
  rescue ActiveStorage::FileNotFoundError
    ''
  end

  def content_size
    errors.add(:content, I18n.t(:too_large)) if content.blob&.byte_size&.>(2.megabytes)
  end

  def remove_after
    return 0 unless remove_at

    remove_at - Time.zone.now
  end

  def remove_after=(value)
    self.remove_at = Time.zone.now + value.to_i
  end

  def auth_key=(key)
    auth = Auth.find_by(key:)
    self.user = auth.user if auth&.user&.valid?
  end

  def self.default_author
    animal = Faker::Creature::Animal.name.titlecase
    adjective = Faker::Adjective.positive.titlecase
    I18n.t(:adjective_animal, adjective:, animal:)
  end

  def remove_at_max
    largest_period = Paste::PERIODS[0][1]
    errors.add(:remove_after, t(:too_long, time: largest_period.inspect)) if remove_after >= largest_period.seconds
  end

  private

  def create_permalink
    self.permalink = SecureRandom.hex(6)
  end

  def enqueue_removal
    PastesCleanupJob.set(wait_until: remove_at).perform_later(self&.id)
  end

  def train_classifier
    return unless saved_change_to_marked_kind? || saved_change_to_marked_by_id?
    return if marked_kind == 'unclassified'
    return if marked_by.nil?

    classifier = Rails.application.config.classifier
    classifier.train marked_kind, code
  end

  def delete_spam
    destroy! if marked_by.present? && marked_kind == 'spam'
  end

  def check_terms
    Term.find_each do |term|
      content = send(term.subject)
      next unless content.include?(term.content)

      if term.action == 'mark_spam'
        self.marked_kind = 'spam'
      elsif term.action == 'remove'
        self.remove_at = 5.seconds.from_now
      end

      break
    end
  end
end

app/controllers/pastes_controller.rb
# frozen_string_literal: true

# The endpoints and pages for pastes
# TODO: Implement authentication from the outside
class PastesController < ApplicationController
  before_action :set_paste, only: %i[show destroy raw]
  before_action :qualify_content, only: :create
  after_action :verify_authorized, except: :index
  after_action :verify_policy_scoped, only: :index
  # Set up activestorage for development
  before_action -> { ActiveStorage::Current.url_options = { host: request.base_url } },
                if: -> { Rails.env.local? }

  def index
    @pastes = if params[:user]
                policy_scope(Paste)&.by_author(User.find_by(username: params[:user]))
              else
                policy_scope(Paste)
              end
  end

  def show
    authorize @paste
  end

  def new
    @paste = authorize Paste.new
  end

  def create
    @paste = authorize Paste.new(paste_params)

    respond_to do |format|
      if @paste.save
        format.html { redirect_to paste_url(@paste), notice: t(:paste_create) }
        format.json { render :show, status: :created, location: @paste }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @paste.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize @paste

    @paste.destroy

    respond_to do |format|
      format.html { redirect_to pastes_url, notice: t(:paste_destroyed) }
      format.json { head :no_content }
    end
  end

  def raw
    authorize @paste, :show?

    redirect_to @paste.content.attachment.url, allow_other_host: true
  end

  def spam
    authorize Paste.new

    if Paste.where(id: pastes_params[:ids]).update(marked_kind: pastes_params[:marked_kinds], marked_by: current_user)
      redirect_to pastes_url, notice: t(:paste_update)
    else
      render :index, status: :unprocessable_entity
    end
  end

  private

  def set_paste
    @paste = Paste.find_by(permalink: params[:paste_permalink] || params[:permalink])

    redirect_to pastes_url, alert: t(:paste_not_found) unless @paste
  end

  def paste_params
    defaults = { marked_kind: @marked_kind }
    defaults[:user_id] = current_user.id if user_signed_in?
    params.require(:paste).permit(:author, :title, :private, :remove_after,
                                  :content, :code, :auth_key).merge(defaults.compact)
  end

  def pastes_params
    params.require(:pastes).permit(:marked_kinds, ids: [])
  end

  def qualify_content
    return unless text_content

    classifier = Rails.application.config.classifier
    @marked_kind = classifier.classify(text_content).downcase
  end

  def text?
    return false if paste_params[:content].blank?

    content_type = paste_params[:content].content_type
    Marcel::Magic.new(content_type).text? || MimeMagic.new(content_type).text?
  end

  def text_content
    return paste_params[:content]&.read&.force_encoding('utf-8') if text?

    paste_params[:code].presence
  end
end

app/helpers/pastes_helper.rb
# frozen_string_literal: true

# Helpers to represent pastes
module PastesHelper
  def represent(attachment)
    return padding(t(:no_attachment)) unless attachment
    return media(attachment) if media?(attachment)

    padding(link_to(attachment.filename, attachment.url))
  end

  def badge(text)
    tag.span(text, class: 'badge text-bg-info')
  end

  def extensions(attachment)
    marcel = Marcel::Magic.new(attachment.content_type).extensions
    mimemagic = MimeMagic.new(attachment.content_type).extensions
    (marcel + mimemagic).uniq
  end

  private

  def image(attachment)
    padding(image_tag(representation_url(attachment)))
  end

  def video(attachment)
    poster = representation_url(attachment) if attachment.representable?
    padding(video_tag(attachment.url, controls: true, poster:))
  end

  def audio(attachment)
    padding(audio_tag(attachment.url, controls: true))
  end

  def document(attachment)
    padding(render('shared/document_info', attachment:, representation: representation_url(attachment)))
  end

  def text(attachment)
    content = attachment.open(&:read).force_encoding('utf-8')
    tag.textarea content, disabled: true, id: 'paste_code',
                          class: 'form-control border-0 rounded-0 rounded-bottom',
                          'data-editor-target': 'textarea',
                          rows: content.lines.count
  end

  def text?(attachment)
    Marcel::Magic.new(attachment.content_type).text? || MimeMagic.new(attachment.content_type).text?
  end

  def media(attachment)
    return image(attachment) if attachment.image? && attachment.representable?
    return video(attachment) if attachment.video?
    return audio(attachment) if attachment.audio?
    return text(attachment) if text?(attachment)

    document(attachment) if attachment.representable?
  end

  def media?(attachment)
    attachment.representable? || attachment.image? || attachment.video? || attachment.audio? || text?(attachment)
  end

  def representation_url(attachment)
    representation = attachment.representation({})
    representation.processed.url
  end

  def padding(content)
    tag.div content, class: 'card-body d-flex justify-content-center position-relative'
  end
end

app/views/pastes/_title.html.haml
:ruby
  title = tag.b paste.title
  author = tag.b paste.author
  expires_in = tag.b distance_of_time_in_words(paste.remove_after),
                     title: paste.remove_at
  private = paste.private ? badge(t(:private)) : ''
  marked = policy(paste).spam? ? badge(t(paste.marked_kind)) : ''
= t(:paste_title_html, title:, private:, marked:, author:, expires_in:)

app/views/pastes/index.html.haml
%h1= t(:pastes_list)
- if policy(Paste.new).spam?
  = form_for(:pastes, url: spam_pastes_path, method: :post) do |f|
    %nav.bg-body-tertiary.rounded.border.mb-3.sticky-top
      .input-group.p-3
        = f.select :marked_kinds,
                   Paste.marked_kinds.keys.index_by { |k| t(k) },
                   {}, class: 'form-select'
        = f.submit 'Set', class: 'btn btn-primary'
    .list-group
      = f.collection_check_boxes(:ids, @pastes, :id, :title) do |c|
        .list-group-item
          = c.check_box class: 'form-check-input', checked: false
          = c.label class: 'form-check-label' do
            = link_to c.object, class: 'text-decoration-none' do
              = render 'pastes/title', paste: c.object
- else
  .list-group
    - @pastes.each do |paste|
      = link_to paste, class: 'list-group-item' do
        = render 'pastes/title', paste:

app/views/pastes/new.html.haml
.h-100{ data: { controller: 'editor',
                'editor-filled-class': 'file-field-filled',
                'editor-full-size-class': 'full-size' } }
  = form_for @paste, html: { 'data-action': 'editor#submit',
                             class: 'd-flex flex-column h-100' } do |f|
    - @paste.errors.full_messages.each do |message|
      .alert.alert-danger
        = message

    .form-floating.mb-3
      - author_attrs = { placeholder: :author, class: 'form-control' }
      - author_attrs[:value] = current_user.username if user_signed_in?
      = f.text_field :author, author_attrs
      = f.label :author, class: 'form-label'
    .form-floating.mb-3
      :ruby
        title_attrs = { placeholder: :title, class: 'form-control' }
        title_attrs[:value] = if user_signed_in?
          t(:user_paste, user: current_user.username)
        else
          t(:anonymous_paste)
        end
      = f.text_field :title, title_attrs
      = f.label :title, class: 'form-label'
    .flex-fill{ data: { action: 'keydown->editor#hideFile' } }
      .border.rounded.bg-body.d-flex.h-100{ 'data-editor-target': 'fullSize' }
        = f.text_area :code,
                      placeholder: :contents_of_the_paste,
                      class: 'form-control border-0 rounded-0 rounded-bottom',
                      'data-editor-target': 'textarea'
        .float-end.sticky-top
          %a.btn.btn-sm.btn-expand{ data: { action: 'editor#expand' },
                                    title: t(:expand) }
            %i.fas.fa-up-right-and-down-left-from-center
          %a.btn.btn-sm.btn-contract{ data: { action: 'editor#contract' },
                                      title: t(:contract) }
            %i.fas.fa-down-left-and-up-right-to-center
    .input-group.mt-3
      = f.file_field :content,
                     class: 'form-control',
                     data: { 'editor-target': 'file',
                             action: 'editor#hideText' }
      #file-remove-button
        %a.btn.btn-secondary.border{ data: { 'editor-target': 'clearFileButton',
                                             action: 'editor#clearFile' } }
          Clear
    .d-flex.justify-content-between.align-items-center.mt-3
      .form-check
        = f.check_box :private, class: 'form-check-input'
        = f.label :private, class: 'form-check-label'
      .d-flex.justify-content-between
        .form-floating.ms-1
          = f.select :remove_after, Paste::PERIODS, { selected: 1.day },
                     { class: 'form-select' }
          = f.label :remove_after, class: 'form-label'
        = f.submit t(:save), class: 'btn btn-primary btn-lg ms-2'

app/views/pastes/show.html.haml
- exts = extensions(@paste.content.attachment)
.card{ data: { controller: 'editor',
               'editor-read-only-value': 'true',
               'editor-extensions-value': exts,
               'editor-full-size-class': 'full-size',
               'editor-target': 'fullSize' } }
  .card-header.pe-1
    .d-flex.justify-content-between.align-items-center.flex-wrap
      .info
        = render 'pastes/title', paste: @paste
      - if @paste.content.attachment
        %ul.list-inline.m-0.d-flex.align-items-center.ms-auto
          %li.list-inline-item
            .span{ data: { controller: 'clipboard' } }
              = tag.input type: 'text', value: paste_url(@paste),
                          class: 'visually-hidden', readonly: 'readonly',
                          'data-clipboard-target': 'source'
              = tag.button class: 'btn btn-link text-info p-0',
                           'data-action': 'clipboard#copy',
                           title: t(:copy_url_to_clipboard) do
                = t(:copy_url_to_clipboard)
          %li.list-inline-item
            = link_to 'Raw', paste_raw_path(@paste)
          - if policy(@paste).destroy?
            %li.list-inline-item
              = button_to t(:remove), paste_path(@paste),
                          method: :delete,
                          class: 'btn p-0 text-danger'
          %li.list-inline-item
            %a.btn.btn-sm.btn-expand{ data: { action: 'editor#expand' },
                                      title: t(:expand) }
              %i.fas.fa-up-right-and-down-left-from-center
            %a.btn.btn-sm.btn-contract{ data: { action: 'editor#contract' },
                                        title: t(:contract) }
              %i.fas.fa-down-left-and-up-right-to-center
  = represent @paste.content.attachment