config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :pastes, only: %w[new create index show destroy], param: :permalink do
    get :raw
  end

  resource :pastes do
    post :spam
  end

  resources :terms, only: %i[index new create destroy]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get '/up' => 'rails/health#show'

  # Omniauth support
  post '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/:provider/callback', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :auths, only: %i[index new create destroy]

  # Defines the root path route ("/")
  root 'pastes#new'

  # Old API support
  post '/', to: 'oldapi#create'
  get '/:permalink', to: 'oldapi#redirect'
end

app/views/layouts/_footer.html.haml
%footer.footer
  .container
    .d-flex.justify-content-between.align-items-center
      .copyright
        = t(:copyright)
      %ul.list-inline.mb-0
        %li.list-inline-item
          = link_to t(:source_code), 'https://github.com/openSUSE/paste-o-o'
        %li.list-inline-item
          = link_to t(:license),
                    'https://github.com/openSUSE/paste-o-o/blob/main/LICENSE'

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-expand-sm
  .container-fluid
    = render 'theme/brand'
    %button.navbar-toggler{ data: { bs: { target: '#navbar-content',
                                          toggle: 'collapse' } },
                            type: 'button',
                            aria: { controls: 'navbar-content',
                                    expanded: 'false',
                                    label: t(:toggle_navigation) } }
      %span.navbar-toggler-icon
    .collapse.navbar-collapse#navbar-content
      %ul.navbar-nav.me-auto
        %li.nav-item
          = link_to t(:create), new_paste_path, class: 'nav-link'
        %li.nav-item
          = link_to t(:recent), pastes_path, class: 'nav-link'
      .navbar-nav
        - if user_signed_in?
          .dropdown.nav-item
            %a.nav-link.dropdown-toggle{ 'aria-expanded': 'false', href: '#',
                                         role: 'button',
                                         'data-bs-toggle': 'dropdown' }
              = avatar current_user
              = current_user.username
            %ul.dropdown-menu.dropdown-menu-end
              %li
                = link_to t(:my_pastes),
                          pastes_path(user: current_user.username),
                          class: 'dropdown-item'
              %li
                = link_to t(:my_keys), auths_path, class: 'dropdown-item'
              - if policy(Term.new).index?
                %li
                  = link_to t(:forbidden_terms),
                            terms_path, class: 'dropdown-item'
              %li
                %hr.dropdown-divider
              %li
                = button_to t(:log_out), '/logout',
                            method: :delete,
                            class: 'dropdown-item text-danger'
        - else
          - auth = Rails.configuration.site[:authentication]
          - if Rails.env.development?
            = render 'sessions/form', provider: { id: 'developer',
                                                  name: 'Developer' }
          - auth&.each_value do |value|
            = render 'sessions/form', provider: { id: value[:name] }
          - if (sign_up_link = Rails.configuration.site[:sign_up_link])
            = link_to t(:sign_up), sign_up_link,
                      class: 'btn btn-primary ms-sm-1 ms-0 mt-1 mt-sm-0'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ content: 'text/html; charset=UTF-8', 'http-equiv': 'Content-Type' }
    %title= Rails.configuration.site[:program_name]
    %meta{ content: 'width=device-width,initial-scale=1', name: 'viewport' }
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', 'data-turbo-track': 'reload'
    = javascript_importmap_tags 'application'
    = favicon_link_tag 'favicon.ico'
  %body
    = render partial: 'layouts/navbar'
    .toast-container.position-fixed.bottom-0.end-0.p-3
      - flash.each do |type, text|
        - type = 'success' if type == 'notice'
        - type = 'danger' if type == 'alert'
        %div{ class: "toast align-items-center text-bg-#{type} border-0 show",
              aria: { atomic: 'true', live: 'assertive' }, role: 'alert' }
          .d-flex
            .toast-body
              = text
            %button.btn-close.me-2.m-auto{ 'aria-label': t(:close),
                                           'data-bs-dismiss': 'toast',
                                           type: 'button' }
    %main.flex-fill.d-flex.h-100
      .container.my-3.flex-fill
        = yield
    = render partial: 'layouts/footer'